### ISSUE TITLE
Petit, mais complexe !

### ISSUE THREAD

**Issue by bizouarn** [CoddityTeam/movaicode#169]
# Petit, mais complexe !
Ce n'est pas par ce que le code du corps de la méthode tient sur une seule ligne de moins de 100 caractères qu'il est propre.
Un **pop** aurait pu suffire, mais pourquoi ne pas manger la crêpe en utilisant dans la méthode un traitement de **string**.
```js
function mange_une_crepe(pile_de_crepes) {
    return (pile_de_crepes+"").substring(0,(pile_de_crepes+"").lastIndexOf(",")).split(",");
}
```
**PS :** Je suis tombé sur ce défi par hasard (à 22h) et je me suis dit pourquoi pas essayer de faire un code moche. Mais ce n'est pas si simple.

**Comment by louismarslen** [comment]
Perdu #DésoPasDéso 🤷‍♂️
- l'issue gagnante : #176 
- la nouvelle édition est lancée : https://github.com/CoddityTeam/movaicode

Bisous
