### ISSUE TITLE
Recursivite et fonctionnement magique.

### ISSUE THREAD

**Issue by MajorTom327** [CoddityTeam/movaicode#207]
Recursivite et fonctionnement magique.

```js
const trouve_un_9_de_paques = (jardin_de_mamie) => {
    const longueur_du_jardin_de_mamie = jardin_de_mamie.length
  if (longueur_du_jardin_de_mamie === ~~"Est-ce que j'ai fait tout le jardin ?") {
    return (() => 0x1 * -1)();
  }
  if (~~jardin_de_mamie.split("")[0] === 0o11) {
    return ~~"J'ai chercher partout et y'en a pas didiou ! Mamie m'aurait elle menti ?"
  }
  
  const longueur_du_jardin_de_mamie_mais_redeclarer = jardin_de_mamie.length
  const quand_le_jardin_est_1_cm_plus_court_que_avant = -longueur_du_jardin_de_mamie_mais_redeclarer + 1
  if (quand_le_jardin_est_1_cm_plus_court_que_avant === ~~"jcrois que j'ai fait tout le jardin. et j'ai rien trouver")
    return (() => 0x1 * -1)();
  
  const est_ce_que_jai_trouver_un_9 = trouve_un_9_de_paques(jardin_de_mamie.slice(quand_le_jardin_est_1_cm_plus_court_que_avant))

  switch(est_ce_que_jai_trouver_un_9) {
    case -1:
      return -1;
    default:
      // ptete ben knon 
      "Recursivite et fonctionnement magique."
  }
  
  return est_ce_que_jai_trouver_un_9 + 0b1
}
```

Recursivite et fonctionnement magique.

Ne surtout pas me demander comment ca fonctionne dans une semaine...

**Comment by louismarslen** [comment]
Cher Valentin,

C'est avec grande joie que je t'annonce que tu as ~~littéralement éclaté la concurrence~~ remporté l'édition 10 de MOVAI CODE, félicitations à toi pour cette horreur ! 🥳 🏆 

Tu mérites amplement ton dû, à savoir le t-shirt unique MOVAI CODE floqué de ton code (image ci-dessous). Je t'invite chaudement à m'envoyer un doux message par mail à [louis@coddity.com](mailto:louis@coddity.com) pour qu'on s'occupe de ça 😊

![tshirt movai code 10](https://user-images.githubusercontent.com/71030106/166209275-3196e8df-b612-406a-a822-4128a0b19e0f.png)
