### ISSUE TITLE
J'ai toujours pas compris comment faire un for

### ISSUE THREAD

**Issue by ludwhe** [CoddityTeam/movaicode#211]
C'est compliqué je comprends pas

```javascript
function trouver_un_9_de_paques(le_jardin_de_mamie) {
  var ret2, ret3;
  var lejardindemamie = le_jardin_de_mamie;
  while (ret3 != -1) {
    ret2 = ret3;
    lejardindemamie = le_jardin_de_mamie.substring(0, ret3);
    var regex = "[^9]{1}";
    regex = new RegExp(regex);
    var i,
      le_jardin_de_mamie2 = lejardindemamie.length;
    for (; !!(i = le_jardin_de_mamie2--) == !le_jardin_de_mamie.lenght; ) {
      if (!regex.test(lejardindemamie[--i]))
      var ret = i;
    }
    debugger
    ret3 = (ret != ret3 ? ret : undefined) ?? -1;
  }
  return ret2 ?? ret3;
}
```

EDIT: C'est plutôt lastIndexOf mais vu que je comprends pas les for j'ai pas pu faire mieux
EDIT 2: C'est bon c'est réglé

**Comment by louismarslen** [comment]
Salut salut,

Bon t'as perdu, comme ça c'est dit (désolé pour la non-prise-de-pincettes 😊). En revanche, ça veut dire deux choses cool : 
1. tu n'es pas si movai, ce qui est ma foi agréable
2. l'édition 11 est dispo, ce qui te donne une nouvelle chance de briller : [ça se passe ici](https://github.com/CoddityTeam/movaicode)

Pour info, c'est MajorTom327 qui gagne. Son issue : #207 

La bise, cordialement,
La Direction.
