### ISSUE TITLE
HÉHO LE SUJET IL Y A UNE COQUILLE DEDANS !!!!

### ISSUE THREAD

**Issue by MathiDEV** [CoddityTeam/movaicode#230]
```return position_d_un_9_de_paques```
Dans le proto de la fonction (ca fait des copié-collés ????)

<send tshirt pls>

**Comment by louismarslen** [comment]
Bien vu, comme un bon movai dev j'ai raté mon pull. C'est corrigé, merci ! 😊

**Comment by chris-codd** [comment]
HAN !!! SES CHO
