### ISSUE TITLE
fun.js

### ISSUE THREAD

**Issue by kdridi** [CoddityTeam/movaicode#28]
# Inside fun.js
```js
const rec = (f) => (...args) => f((...args) => rec(f)(...args), ...args)
const ter = (s) => (n) => (e) => (s.length ? n() : e())
const rev = (s) => ter(s)(() => rec((r, x, ...xs) => ter(xs)(() => [...r(...xs), ...x])(() => [x]))(...Array.from(s)))(() => []).join('')
process.argv.forEach((s, i) => (i > 1 ? console.log(rev(s)) : false))
```
# Run fun.js
```sh
node fun.js 'Hello, world!' 'This is Movai Code'
```
# Output
```
!dlrow ,olleH
edoC iavoM si sihT
```

**Comment by louismarslen** [comment]
Cher Karim, j'ai le plaisir et l'honneur de vous annoncer que vous n'avez PAS gagné le concours MOVAI CODE. Ce qui fait de vous un EKSSELAN Codeur. 

SPOILER : j'espère qu'on aura le plaisir de recevoir votre participation à l'episode 2 du MOVAI CODE (stay tuned).

Bravo toutefois pour votre belle contribution 😊
