### ISSUE TITLE
CSS Rotate

### ISSUE THREAD

**Issue by yanbonnel** [CoddityTeam/movaicode#39]
Codepen : https://codepen.io/ybonnel/pen/YzqOmVz

Javascript : 
```
function magicFunction(event) {
  const revertDiv = document.querySelector('.revert')
  revertDiv.innerHTML = event.target.value.split('').map(car =>
    `<span>${car}</span>`
  ).join('')
  
}

window.onload = () => document.getElementById('input').addEventListener('keyup', magicFunction)
```

CSS : 
```
#input {
  margin-right: 10px;
}

.revert {
  transform: rotateY(180deg);
  display: inline-block;
}

.revert span {
  display: inline-block;
  transform: rotateY(180deg);
}
```

HTML : 
```
<html>
  <body>
  <input id="input" placeHolder="Revert me"/>
  
  <div class="revert">
  </div>
  </body>
</html>
```

**Comment by yanbonnel** [comment]
Je suis à peu près sûr qu'on peux se passer de JS, faut que je trouve un moyen :)

**Comment by louismarslen** [comment]
Cher Yan, j'ai le plaisir et l'honneur de vous annoncer que vous n'avez PAS gagné le concours MOVAI CODE. Ce qui fait de vous un EKSSELAN Codeur. 

SPOILER : j'espère qu'on aura le plaisir de recevoir votre participation à l'episode 2 du MOVAI CODE (stay tuned).

Bravo toutefois pour votre belle contribution 😊

**Comment by louismarslen** [comment]
Je fais un peu de ménage dans les issues -> d'ailleurs go participer à [l'édition 5](https://github.com/CoddityTeam/movaicode)
