### ISSUE TITLE
APL

### ISSUE THREAD

**Issue by wamaral** [CoddityTeam/movaicode#40]
`⌽`

**Comment by louismarslen** [comment]
Cher Wagner, j'ai le plaisir et l'honneur de vous annoncer que vous n'avez PAS gagné le concours MOVAI CODE. Ce qui fait de vous un EKSSELAN Codeur. 

SPOILER : j'espère qu'on aura le plaisir de recevoir votre participation à l'episode 2 du MOVAI CODE (stay tuned).

Bravo toutefois pour votre belle contribution 😊
