### ISSUE TITLE
HTML texte en hebreu/arabe

### ISSUE THREAD

**Issue by Florent-Bouisset** [CoddityTeam/movaicode#47]
Petit hack pour utiliser la fonctionnalité qui permet d'afficher le texte de droite à gauche pour les langues qui se lisent de cette manière comme l'hebreu ou l'arabe :smile: 
Copier le code suivant dans un fichier .html et l'ouvrir avec son navigateur pour tester :rocket: 

```<!DOCTYPE html>
<html>
    <body>
        <bdo dir="rtl">I love this kind of challenge ! </bdo>
        <button onclick="reverse()">Reverse</button>
    </body>
    <script>
        function reverse(){
            if(document.getElementsByTagName("bdo")[0].getAttribute("dir") === 'ltr')
            {
                document.getElementsByTagName("bdo")[0].setAttribute("dir", "rtl"); 
            }
            else {
                document.getElementsByTagName("bdo")[0].setAttribute("dir", "ltr"); 
            }
        }
    </script>
</html>
```

**Comment by louismarslen** [comment]
Cher Florent, j'ai le plaisir et l'honneur de vous annoncer que vous n'avez PAS gagné le concours MOVAI CODE. Ce qui fait de vous un EKSSELAN Codeur. 

SPOILER : j'espère qu'on aura le plaisir de recevoir votre participation à l'episode 2 du MOVAI CODE (stay tuned).

Bravo toutefois pour votre belle contribution 😊

**Comment by louismarslen** [comment]
Je fais un peu de ménage dans les issues -> d'ailleurs go participer à [l'édition 5](https://github.com/CoddityTeam/movaicode)
