### ISSUE TITLE
Appel de fonction par la barbe de merlin

### ISSUE THREAD

**Issue by Taink** [CoddityTeam/movaicode#51]
Ma fabuleuse syntaxe ne semble pas être reconnue donc je fournis ici en fichier mon script.
[super.txt](https://github.com/CoddityTeam/movaicode/files/5281284/super.txt)

**Comment by mehdi-dalil** [comment]
```js
var myfunc=(__)=>{var _=[1,0,-1,0,[],'codePointAt','push','fromCodePoint','join','','toString'];while(__[_[5]](_[3]+_[0])) _[3]=_[3]+_[0];_[3]=_[3]+_[0];while(_[3]>_[1]) _[4][_[6]](String[_[7]](__[_[5]](_[3]=_[3]+_[2])));return _[4][_[8]](_[9])[_[10]]()}

console.log(myfunc('Hello你♲★☃wôrld!'))
```

ca m'a l'air bon non ?

**Comment by Taink** [comment]
Ah merci 😅
J'ai dû faire une fausse manip

**Comment by louismarslen** [comment]
Cher @Taink, j'ai le plaisir et l'honneur de vous annoncer que vous n'avez PAS gagné le concours MOVAI CODE. Ce qui fait de vous un EKSSELAN Codeur. 

SPOILER : j'espère qu'on aura le plaisir de recevoir votre participation à l'episode 2 du MOVAI CODE (stay tuned).

Bravo toutefois pour votre belle contribution 😊

**Comment by louismarslen** [comment]
Je fais un peu de ménage dans les issues -> d'ailleurs go participer à [l'édition 5](https://github.com/CoddityTeam/movaicode)
