### ISSUE TITLE
ses traits visuelle 

### ISSUE THREAD

**Issue by geneixda** [CoddityTeam/movaicode#69]
clique sur le carré bleu

liste de mots et mot a chercher personnalisable

très satisfait du temps de calcul

(dézipper l'archive pour recup le fichier excel avec macro)

`
[Movaicode2 by geneixda.zip](https://github.com/CoddityTeam/movaicode/files/5658759/Movaicode2.by.geneixda.zip)

`

**Comment by louismarslen** [comment]
Hello geneixda, j'ai une bonne et une mauvaise (movaize) nouvelle : 

- tu n'as pas gagné MOVAI CODE 2
- par conséquent, tu es auffissielement un bon développeur

Bravo et pas bravo donc ! 😊

PS : oui c'est un copié-collé, j'ai pas suffisamment d'inspiration pour faire 26 commentaires différents...

**Comment by louismarslen** [comment]
Je fais un peu de ménage dans les issues -> d'ailleurs go participer à [l'édition 5](https://github.com/CoddityTeam/movaicode)
