### ISSUE TITLE
p-r_o.g_r-a.m.js

### ISSUE THREAD

**Issue by clitzinger** [CoddityTeam/movaicode#70]
Du moche, illisible, lourd et qui peut péter à la moindre occasion ?
Ravi de pouvoir donner le pire de moi-même avec ce code dont je ne peux pas être fier ![image](https://user-images.githubusercontent.com/11597998/101481236-245cd880-3955-11eb-823c-232f512c05fa.png)

Bon courage à celui qui va relire cette horreur !

```javascript
this.a = [
  "cadeau",
  "pourri",
  "cadeau",
  "revendre",
  "écharpe",
  "transformer",
  "smartbox",
  "pyrénéens",
  "goldeneye64",
  "cadeau",
];

this.b = [];
for (var a = this.a.length - 1; a >= 0; a--) {
  for (var b = this.a[a].length - 1; b >= 0; b--) this.b.push(this.a[a][b]);
}

this.c = [];
for (var c = this.b.length - 1; c >= this.b.length - 6; c--) {
  this.c.push(this.b[c]);
}

this.d = [];
this.e = 0;
this.f = 0;
for (var d = this.b.length - 1; d >= 0; d--) {
  this.d.push(this.b[d]);
  this.f +=
    this.d[this.d.length - 1] == this.c[this.d.length - 1]
      ? 1
      : (() => {
          this.d = [];
          this.f = 0;
          return 0;
        })();
  if (this.f == 6) {
    this.e += 1;
    this.f = 0;
    this.d = [];
  }
}

console.log(this.e);
```
Pour tester :
```javascript
node p-r_o.g_r-a.m.js
> 3
```

**Comment by louismarslen** [comment]
Hello Christophe, j'ai une bonne et une mauvaise (movaize) nouvelle : 

- tu n'as pas gagné MOVAI CODE 2
- par conséquent, tu es auffissielement un bon développeur

Bravo et pas bravo donc ! 😊

PS : oui c'est un copié-collé, j'ai pas suffisamment d'inspiration pour faire 26 commentaires différents...

**Comment by louismarslen** [comment]
Je fais un peu de ménage dans les issues -> d'ailleurs go participer à [l'édition 5](https://github.com/CoddityTeam/movaicode)
