### ISSUE TITLE
[movaicode/3] Les temps sont durs

### ISSUE THREAD

**Issue by YannBoucherUtc** [CoddityTeam/movaicode#92]
Dans un monde post-apocalyptique où les octets sont des denrées aussi rares que les sources d'eau, les adeptes du movaicode sont le seul espoir de l'humanité. Eux seuls sont capable de pondre un code obscur, pourri et incompréhensible mais fonctionnel et pouvant tourner sur les quelques bytes restants à disposition du genre humain. 

En 97 caractères : 
```c
#define p printf(
main(a,s)char**s;{p"[\"");for(--*++s;a=*++*s;)a^32?p"%c",a):p"\", \"");p"\"]");}
```
Usage : 
```
./split "Bonjour le monde !"
> ["Bonjour", "le", "monde", "!"]
```

**Comment by louismarslen** [comment]
Je fais un peu de ménage dans les issues -> d'ailleurs go participer à [l'édition 5](https://github.com/CoddityTeam/movaicode)
