### ISSUE TITLE
Du code Solidity dans une string JS

### ISSUE THREAD

**Issue by Thykof** [CoddityTeam/movaicode#96]
L'idée est d'écrire du code Solidity dans une chaîne de caractère en JavaScript. Ensuite, compiler ce code, déployer le smart contrat et l'utiliser pour `split` "DAFT PUNK".

https://github.com/Thykof/movaicode3

**Comment by Oli8** [comment]
120$ par split ? 🙂

**Comment by Thykof** [comment]
Plutôt dans les $40 pour le premier, ensuite $3.5 !

**Comment by louismarslen** [comment]
Je fais un peu de ménage dans les issues -> d'ailleurs go participer à [l'édition 5](https://github.com/CoddityTeam/movaicode)
